apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sobouriic/sobouric-inception.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
