Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"


  # SERVER MACHINE

  config.vm.define "sobouricS" do |server|
    server.vm.hostname = "sobouricS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "sobouricS"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  # SERVER-WORKER MACHINE
 
  config.vm.define "sobouricSW" do |worker|
    worker.vm.hostname = "sobouricSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "sobouricSW"
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end

end
